presets:
- labels:
    preset-compute-service-account: "true" # Service account with "Compute Admin" and "Compute OS Admin Login" roles
  env:
    - name: GOOGLE_APPLICATION_CREDENTIALS
      value: /etc/service-account/compute-service-account.json
  volumes:
  - name: compute-service-account
    secret:
      secretName: compute-service-account
  volumeMounts:
  - name: compute-service-account
    mountPath: /etc/service-account
    readOnly: true

periodics:
- interval: 10m
  agent: kubernetes
  name: echo-test
  spec:
    containers:
    - image: alpine
      command: ["/bin/date"]
presubmits:
  kyma-incubator/varkes:
  - agent: kubernetes
    name: varkes-test
    trigger: "(?m)^/test varkes"
    rerun_command: "/test varkes"
    context: varkes-test
    always_run: true
    run_if_changed: "odata-mock/.*"
    skip_report: false
    spec:
      containers:
      - image: badrawi/varkes_image:v14