periodics:
- interval: 10m
  agent: kubernetes
  name: echo-test
  spec:
    containers:
    - image: alpine
      command: ["/bin/date"]
postsubmits:
  kyma-project/test-infra:
  - name: test-postsubmit
    agent: kubernetes
    spec:
      containers:
      - image: alpine
        command: ["/bin/printenv"]
  kyma-incubator/varkes:
  - name: test-presubmit
    trigger: "(?m)^/test this"
    rerun_command: "/test this"
    context: test-presubmit
    always_run: true
    skip_report: false
    agent: kubernetes
    spec:
      containers:
      - image: alpine
        command: ["/bin/printenv"]
presubmits:
  kyma-project/test-infra:
  - name: test-presubmit
    trigger: "(?m)^/test this"
    rerun_command: "/test this"
    context: test-presubmit
    always_run: true
    skip_report: false
    agent: kubernetes
    spec:
      containers:
      - image: alpine
        command: ["/bin/printenv"]
  kyma-incubator/varkes:
  - name: test-presubmit
    trigger: "(?m)^/test this"
    rerun_command: "/test this"
    context: test-presubmit
    always_run: true
    skip_report: false
    agent: kubernetes
    spec:
      containers:
      - image: alpine
        command: ["/bin/printenv"]
  - agent: kubernetes
    name: varkes-test
    trigger: "(?m)^/test varkes"
    rerun_command: "/test varkes"
    context: varkes-test
    always_run: true
    skip_report: false
    spec:
      containers:
      - image: badrawi/varkes_image:v14
        volumeMounts:
        - mountPath: /var/run/docker.sock
          name: docker-socket-volume
        securityContext:
          privileged: true
  suleymanakbas91/kyma:
  - name: test-prow
    trigger: "(?m)^/test prow"
    rerun_command: "/test prow"
    context: test-prow
    always_run: true
    skip_report: false
    agent: kubernetes
    spec:
      containers:
      - image: eu.gcr.io/kyma-project/snapshot/test/prow:test2
        name: test-prow
        volumeMounts:
        - mountPath: /var/run/docker.sock
          name: docker-socket-volume
        securityContext:
          privileged: true
      volumes:
        - name: docker-socket-volume
          hostPath:
            path: /var/run/docker.sock
            type: File