presets:
- labels:
    preset-compute-service-account: "true" # Service account with "Compute Admin" and "Compute OS Admin Login" roles
  env:
    - name: GOOGLE_APPLICATION_CREDENTIALS
      value: /etc/service-account/compute-service-account.json
  volumes:
  - name: compute-service-account
    secret:
      secretName: compute-service-account
  volumeMounts:
  - name: compute-service-account
    mountPath: /etc/service-account
    readOnly: true

periodics:
- interval: 10m
  agent: kubernetes
  name: echo-test
  spec:
    containers:
    - image: alpine
      command: ["/bin/date"]
presubmits:
  kyma-incubator/varkes:
  - agent: kubernetes
    name: varkes-test
    trigger: "(?m)^/test varkes"
    rerun_command: "/test varkes"
    context: varkes-test
    always_run: true
 #   run_if_changed: "odata-mock/.*"
    skip_report: false
    spec:
      containers:
      - image: badrawi/varkes_image:v15
        name: mainD
        command: ['docker', 'run', '-p', '10000:10000', 'badrawi/varkes-openapi:v1']
        env: 
          - name: DOCKER_HOST 
            value: tcp://localhost:10000
      -image: badrawi/varkes-openapi:v1
  suleymanakbas91/kyma:
  - name: kyma-integration
    trigger: "(?m)^/test kyma-integration"
    rerun_command: "/test kyma-integration"
    context: kyma-integration
    skip_report: false # from documentation: SkipReport skips commenting and setting status on GitHub.
    max_concurrency: 10
    labels:
      preset-compute-service-account: "true"
    spec:
      containers:
      - image: eu.gcr.io/kyma-project/snapshot/test/integration:0.0.1