APP_NAME = varkes-cockpit
IMG = $(DOCKER_PUSH_REPOSITORY)$(DOCKER_PUSH_DIRECTORY)/$(APP_NAME)
resolve:
	npm install

docker-build: ;

docker-push: ;

clean:
	rm -rf ./node_modules

run:
	npm start