apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: example-stress-mock
  labels:
    app: example-stress-mock
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: example-stress-mock
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
        - image: eu.gcr.io/kyma-project/incubator/varkes-example-stress-mock:latest
          imagePullPolicy: Always
          name: example-stress-mock
          ports:
            - name: http
              containerPort: 10000
          env:
            - name: DEBUG
              value: "true"
            - name: OPENAPI
              value: "100"
            - name: ODATA
              value: "100"
            - name: EVENT
              value: "100"
---
apiVersion: v1
kind: Service
metadata:
  name: example-stress-mock
  labels:
    app: example-stress-mock
spec:
  ports:
    - name: http
      port: 10000
  selector:
    app: example-stress-mock
---
apiVersion: gateway.kyma-project.io/v1alpha2
kind: Api
metadata:
  labels:
    app: example-stress-mock
  name: example-stress-mock
spec:
  hostname: example-stress-mock
  service:
    name: example-stress-mock
    port: 10000
