openapi: "3.0.0"
info:
  description: "Courses Webservices"
  version: "2.0"
  title: "Courses Webservices"
basePath: "/api1"
consumes:
  - "application/json"
produces:
  - "application/json"
  - "application/xml"
paths:
  /courses:
    get:
      summary: "Get a list of available courses."
      description: "Lists all available courses."
      consumes:
        - "application/json"
      produces:
        - "application/xml"
        - "application/json"
      responses:
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/CoursesDTO"
        401:
          description: "Unauthorized"
        403:
          description: "Forbidden"
        404:
          description: "Not Found"
    post:
      summary: "insert courses"
      description: "Given a list of course in body, insert data."
      consumes:
        - "application/json"
      produces:
        - "application/xml"
        - "application/json"
      parameters:
        - in: "body"
          name: "componentIdList"
          description: "List of Component identifiers"
          required: true
          schema:
            type: "object"
            course:
              $ref: "#/definitions/CourseDTO"
      responses:
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/CoursesDTO"
        201:
          description: "Created"
        401:
          description: "Unauthorized"
        403:
          description: "Forbidden"
        404:
          description: "Not Found"
    security:
      - oauth2_Password: []
      - oauth2_client_credentials: []
  /coursesbyId/{id}:
    get:
      summary: "Get a list of available courses."
      description: "Lists supported payment card types."
      consumes:
        - "application/json"
      produces:
        - "application/xml"
        - "application/json"
      parameters:
        - name: "id"
          in: "path"
          description: "course identifier"
          required: true
          type: "string"
          default: "1"
      responses:
        200:
          description: "OK"
          schema:
            course:
              code:
                type: "string"
              name:
                type: "string"
            default:
              course:
                code: "C1"
                name: "course1"
        401:
          description: "Unauthorized"
        403:
          description: "Forbidden"
        404:
          description: "Not Found"
    security:
      - oauth2_Password: []
      - oauth2_client_credentials: []
definitions:
  CoursesDTO:
    type: "array"
    items:
      ref: "#/definitions/CourseDTO"
  CourseDTO:
    code:
      type: "string"
    name:
      type: "string"
