openapi: "3.0.0"
info:
  description: "Commerce Webservices Version 2"
  version: "2.0"
  title: "Commerce Webservices V2"
basePath: "/api2"
consumes:
  - "application/json"
produces:
  - "application/json"
  - "application/xml"
paths:
  /schools:
    get:
      summary: "Get a list of available schools."
      description: "Lists all available schools."
      consumes:
        - "application/json"
      produces:
        - "application/xml"
        - "application/json"
      responses:
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/SchoolsDTO"
        401:
          description: "Unauthorized"
        403:
          description: "Forbidden"
        404:
          description: "Not Found"
    post:
      summary: "insert schools"
      description: "Given a list of school in body, insert data."
      consumes:
        - "application/json"
      produces:
        - "application/xml"
        - "application/json"
      parameters:
        - in: "body"
          name: "componentIdList"
          description: "List of Component identifiers"
          required: true
          schema:
            type: "object"
            school:
              $ref: "#/definitions/SchoolDTO"
      responses:
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/SchoolsDTO"
        201:
          description: "Created"
        401:
          description: "Unauthorized"
        403:
          description: "Forbidden"
        404:
          description: "Not Found"
    security:
      - oauth2_Password: []
      - oauth2_client_credentials: []
  /schoolsbyId/{id}:
    get:
      summary: "Get a list of available schools."
      description: "Lists supported payment card types."
      consumes:
        - "application/json"
      produces:
        - "application/xml"
        - "application/json"
      parameters:
        - name: "id"
          in: "path"
          description: "school identifier"
          required: true
          type: "string"
          default: "1"
      responses:
        200:
          description: "OK"
          schema:
            school:
              code:
                type: "string"
              name:
                type: "string"
            default:
              school:
                code: "C1"
                name: ""
        401:
          description: "Unauthorized"
        403:
          description: "Forbidden"
        404:
          description: "Not Found"
    security:
      - oauth2_Password: []
      - oauth2_client_credentials: []
definitions:
  SchoolsDTO:
    type: "array"
    items:
      ref: "#/definitions/SchoolDTO"
  SchoolDTO:
    code:
      type: "string"
    name:
      type: "string"
