swagger: "2.0"
info:
  description: "Commerce Webservices Version 2"
  version: "2.0"
  title: "Commerce Webservices V2"
basePath: "/api2"
consumes:
  - "application/json"
produces:
  - "application/json"
  - "application/xml"
paths:
  /schools:
    get:
      summary: "Get a list of available schools."
      description: "Lists all available schools."
      consumes:
        - "application/json"
      produces:
        - "application/xml"
        - "application/json"
      responses:
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/SchoolDTO"
        401:
          description: "Unauthorized"
        403:
          description: "Forbidden"
        404:
          description: "Not Found"
    post:
      summary: "insert school"
      description: "Given a list of course in body, insert data."
      consumes:
        - "application/json"
      produces:
        - "application/xml"
        - "application/json"
      parameters:
        - in: "body"
          name: "componentIdList"
          description: "List of Component identifiers"
          required: true
          schema:
            $ref: "#/definitions/SchoolDTO"
      responses:
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/SchoolDTO"
        201:
          description: "Created"
        401:
          description: "Unauthorized"
        403:
          description: "Forbidden"
        404:
          description: "Not Found"
    security:
      - oauth2_Password: []
      - oauth2_client_credentials: []
  /authorizationserver/oauth/token:
    post:
      summary: "Get OAuth2 access token"
      description: "Returns the acess token for Kyma"
      consumes:
        - "application/x-www-form-urlencoded"
      produces:
        - "application/xml"
        - "application/json"
      parameters:
        - in: "body"
          name: "parameters"
          description: "List of Component identifiers"
          required: true
          schema:
            type: "object"
            properties:
              client_id:
                type: "string"
              client_secret:
                type: "string"
              grant_type:
                type: "string"
      responses:
        200:
          description: "OK"
          schema:
            type: "object"
            properties:
              access_token_url:
                type: "string"
            default:
              token: "3333"
        404:
          description: "Not Found"
  /trial_endpoint:
    get:
      summary: "Get OAuth2 access token"
      description: "Returns the acess token for Kyma"
      consumes:
        - "application/json"
      produces:
        - "application/xml"
        - "application/json"
      responses:
        200:
          description: "OK"
          schema:
            type: "object"
            properties:
              token:
                type: "string"
            default:
              token: "3333"
        404:
          description: "Not Found"
definitions:
  SchoolDTO:
    type: "array"
    items:
      areacode:
        type: "string"
      name:
        type: "string"

