name: build-and-publish

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - master
  release:
    types: [published]
  workflow_dispatch: {}
jobs:
  build:
    runs-on: ubuntu-latest
    permissions: 
      contents: read
      packages: write 
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 14
          scope: '@varkes'
          registry-url: https://npm.pkg.github.com/@varkes
      - name: Install and Build
        run: make resolve
      - name: Test
        run: make validate
      - name: Publish
        run: npx lerna publish from-package --yes --registry='https://npm.pkg.github.com/@varkes'
        if: github.event_name == 'release'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
